defaults: &defaults
  base_url: "http://192.168.1.7:3000"
  grunt_url: "http://localhost:3001"
  alpha_code: "a999"
  image_store: "/home/stevej/LongWebcam/data/ImageStore"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults