source 'https://rubygems.org'

gem 'rails', '2.3.18'
gem 'mysql2'
gem 'json'
gem 'bcrypt-ruby', '3.0.1'
gem 'activerecord-mysql2-adapter', '0.0.3'
gem 'libxml-ruby', '2.6.0'
gem 'rmagick', '2.13.2'

group :development do
  gem 'annotate', '2.5.0'

end

