source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.0.2'

# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.4.5'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.11'

# XML handler
gem 'libxml-ruby', '~> 3.0.0'

# Image processing
gem 'rmagick', '~> 2.16.0'

# XML Builder
gem 'builder', '~> 3.2.3'

